image: node:latest

stages:
  - build
  - test
cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - cd registry
    - node index.js

test:
  stage: test
  tags:
    - docker
  script:
    - console.log("Tests haven't been added yet....")

